# Generated by Django 3.1.7 on 2021-04-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COntact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=123)),
                ('email', models.CharField(blank=True, default=None, max_length=123)),
                ('phone', models.CharField(blank=True, default=None, max_length=123)),
                ('address', models.CharField(blank=True, default=None, max_length=123)),
                ('Rail', models.CharField(blank=True, default=None, max_length=123)),
                ('station', models.CharField(blank=True, default=None, max_length=123)),
                ('locality', models.CharField(blank=True, default=None, max_length=123)),
                ('work', models.CharField(blank=True, default=None, max_length=123)),
            ],
        ),
    ]
