# Generated by Django 3.1.7 on 2021-05-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default=None, max_length=123)),
                ('email', models.CharField(blank=True, default=None, max_length=123)),
                ('add', models.CharField(blank=True, default=None, max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(blank=True, default=None, max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Saif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default=None, max_length=123)),
                ('phone', models.CharField(blank=True, default=None, max_length=123)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='times',
            field=models.CharField(max_length=123, null=True),
        ),
    ]
