# Generated by Django 3.1.7 on 2021-04-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='times',
            field=models.CharField(max_length=123, null=True),
        ),
    ]
