# Generated by Django 3.2.1 on 2021-05-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210502_1732'),
        ('home', '0002_contact_times'),
    ]

    operations = [
    ]
