# Generated by Django 3.1.7 on 2021-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=123)),
                ('lastname', models.CharField(blank=True, default=None, max_length=123)),
                ('phone', models.CharField(blank=True, default=None, max_length=123)),
            ],
        ),
    ]
