# Generated by Django 3.2.1 on 2021-05-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_merge_0002_auto_20210502_1732_0002_contact_times'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saif',
        ),
    ]
