# Generated by Django 3.2.1 on 2021-05-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_saif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=None, max_length=123)),
                ('phone', models.CharField(blank=True, default=None, max_length=123)),
            ],
        ),
    ]
